config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :review_likes
      get :game_likes
      get :maker_likes
      get :favindex
    end
  end
  
  
  
  resources :favorites_users, only: [:create, :destroy]
  resources :favorites_reviews, only: [:create, :destroy]
  resources :favorites_games, only: [:create, :destroy]
  resources :favorites_makers, only: [:create, :destroy]
  resources :makers, only: [:new, :create]
  resources :games, only: [:new, :create]
  resources :reviews, only: [:index, :new, :create, :destroy, :edit, :update] do
    resources :comments, only: [:new, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :review, dependent: :destroy
  has_many :comment
  has_many :favorites_users
  has_many :followings, through: :favorites_users, source: :follow
  has_many :reverses_of_favorites_user, class_name: 'FavoritesUser', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_favorites_user, source: :user
  has_many :favorites_reviews
  has_many :favreviews, through: :favorites_reviews, source: :review
  has_many :favorites_games
  has_many :favgames, through: :favorites_games, source: :game
  has_many :favorites_makers
  has_many :favmakers, through: :favorites_makers, source: :maker
  
  def follow(other_user)
    unless self == other_user
      self.favorites_users.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    favorites_user = self.favorites_users.find_by(follow_id: other_user.id)
    favorites_user.destroy if favorites_user
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def review_like(review)
    favorites_reviews.find_or_create_by(review_id: review.id)
  end

  def review_unlike(review)
    favorites_review = favorites_reviews.find_by(review_id: review.id)
    favorites_review.destroy if favorites_review
  end

  def  favreview?(review)
    self.favreviews.include?(review)
  end
  
  def game_like(game)
    favorites_games.find_or_create_by(game_id: game.id)
  end

  def game_unlike(game)
    favorites_game = favorites_games.find_by(game_id: game.id)
    favorites_game.destroy if favorites_game
  end

  def  favgame?(game)
    self.favgames.include?(game)
  end
  
  
  
  
  def maker_like(maker)
    favorites_makers.find_or_create_by(maker_id: maker.id)
  end

  def maker_unlike(maker)
    favorites_maker = favorites_makers.find_by(maker_id: maker.id)
    favorites_maker.destroy if favorites_maker
  end
  
  def  favmaker?(maker)
    self.favmakers.include?(maker)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :update, :followings]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.review.order(id: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
 
    if current_user == @user
 
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        render :edit
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :edit
      end   
 
    else
    redirect_to root_url
    end
  end
  
  def favindex
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
  end
  
  def review_likes
    @user = User.find(params[:id])
    @favreviews = @user.favreviews.page(params[:page])
  end
  
  def game_likes
    @user = User.find(params[:id])
    @favgames = @user.favgames.page(params[:page])
  end
  
  def maker_likes
    @user = User.find(params[:id])
    @favmakers = @user.favmakers.page(params[:page])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation)
  end
end

app/views/users/_user_following.html.erb
<ul class="list-unstyled">
  <li><h4>お気に入りユーザ一覧</h4></li> 
  <br>
  <% followings.each do |following| %>
    <li><h5><%= following.name %>  <%= link_to 'ユーザ詳細へ', user_path(following), class: 'btn btn-sm btn-primary' %></h5></li>
  <% end %>
</ul>
</div>

app/views/users/_user_game_likes.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<ul class="list-unstyled">
  <li><h4>お気に入りゲーム一覧</h4></li> 
  <br>
  <% favgames.each do |favgame| %>
    <li><h5>ゲームタイトル:　<%= favgame.title %></h5></li>
    
    <p class="btn btn-info btn-sm">このゲームのレビューの表示・非表示</p>
    <ul class="list-unstyled" style="display: none;">
      <li>
        <% games= favgame.review %>
        <% games.each do |game| %>
          <br>
          ユーザネーム:　<%= game.user.name %>
          <br>
          評価:　<%= game.score %>
          <br>
          レビュー:　<%= game.review %>
          <br>
          <br>
          --------------------------------
        <% end %>
      </li>
    </ul>
        
    <br>
    <%= render 'favorites_games/like_button', game: favgame %>
    <br>
    <br>
  <% end %>
</ul>
</div>


<script>
$(function(){
 
    //.accordion1の中のp要素がクリックされたら
	$('.list-unstyled p').click(function(){
 
		//クリックされた.accordion1の中のp要素に隣接するul要素が開いたり閉じたりする。
		$(this).next('ul').slideToggle();
 
	});
});
</script>

app/views/users/_user_maker_likes.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<ul class="list-unstyled">
  <li><h4>お気に入りメーカー一覧</h4></li> 
  <br>
  <% favmakers.each do |favmaker| %>
    <li><h5>発売元メーカー:　<%= favmaker.maker %></h5></li>
    
    <p class="btn btn-info btn-sm">このメーカーのゲームの表示・非表示</p>
    <ul class="list-unstyled" style="display: none;">
      <li>
        <% makers= favmaker.game %>
        <% makers.each do |maker| %>
          <br>
          ゲームタイトル:　<%= maker.title %>　<%= render 'favorites_games/like_button', game: maker %>
          <br>
          --------------------------------
        <% end %>
      </li>
    </ul>
    
    <br>
    <%= render 'favorites_makers/like_button', maker: favmaker %>
    <br>
    <br>
  <% end %>
</ul>
</div>


<script>
$(function(){
 
    //.accordion1の中のp要素がクリックされたら
	$('.list-unstyled p').click(function(){
 
		//クリックされた.accordion1の中のp要素に隣接するul要素が開いたり閉じたりする。
		$(this).next('ul').slideToggle();
 
	});
});
</script>

app/views/users/_user_review_likes.html.erb
<ul class="list-unstyled">
  <li><h4>お気に入りレビュー一覧</h4></li> 
  <br>
  <% favreviews.each do |favreview| %>
    <li><h5>ユーザネーム:　<%= favreview.user.name %></h5></li>
    <li><h5>ゲームタイトル:　<%= favreview.game.title %></h5></li>
    <li><h5>発売元メーカー:　<%= favreview.game.maker.maker %></h5></li>
    <li><h5>評価:　<%= favreview.score %></h5></li>
    <li><h5>レビュー:　<%= favreview.review %></h5></li>
    <br>
    <%= render 'favorites_reviews/like_button', review: favreview %>
    <br>
    <br>
  <% end %>
</ul>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h4>ユーザ情報編集</h4>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, 'プロフィール画像' %><br>
        <%= f.file_field :image %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, '新パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, '新パスワード確認用' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '編集を完了する', class: 'btn btn-primary btn-sm' %>
      <br>
      <br>
      <%= link_to 'キャンセル', user_path(current_user), class: 'btn btn-sm btn-dark' %>
    <% end %>
  </div>
</div>

app/views/users/favindex.html.erb
<div class="text-center">
    <h3>お気に入り一覧</h3>
    <br>
    <br>
    <br>
<ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<% favindex_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favindex_user_path(@user)) %>">お気に入りユーザ</a></li>
      <li class="nav-item"><a href="#" class="nav-link <%#= 'active' if current_page?(followings_user_path(@user)) %>">お気に入りレビュー</a></li>
      <li class="nav-item"><a href="#" class="nav-link <%#= 'active' if current_page?(followings_user_path(@user)) %>">お気に入りゲームタイトル</a></li>
      <li class="nav-item"><a href="#" class="nav-link <%#= 'active' if current_page?(followings_user_path(@user)) %>">お気に入り発売元メーカー</a></li>
</ul>

<%= render 'user_following', followings: @followings %>

app/views/users/game_likes.html.erb
<div class="text-center">
    <h3>お気に入り一覧</h3>
    <br>
    <br>
    <br>
<ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= favindex_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favindex_user_path(@user)) %>">お気に入りユーザ</a></li>
      <li class="nav-item"><a href="<%= review_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(review_likes_user_path(@user)) %>">お気に入りレビュー</a></li>
      <li class="nav-item"><a href="<%= game_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(game_likes_user_path(@user)) %>">お気に入りゲームタイトル</a></li>
      <li class="nav-item"><a href="<%= maker_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(maker_likes_user_path(@user)) %>">お気に入り発売元メーカー</a></li>
</ul>

<%= render 'user_game_likes', favgames: @favgames %>

app/views/users/index.html.erb
<% users = @users %>
<% if users.any? %>
  <div class="text-center">
    <h1>ユーザ一覧</h1>
    <br>
    <br>
    <br>
    <ul class="list-unstyled">
      <% users.each do |user| %>
      <li><%= image_tag user.image.thumb100.to_s %></li>
      <li><%= link_to 'ユーザ詳細へ', user_path(user), class: 'btn btn-sm btn-primary' %></li>
      <br>
      <li>ユーザネーム　<%= user.name %></li>
      <br>
        <h5>最近のレビュー</h5>
        <% reviews = user.review.order(id: :desc).limit(3) %>
        <% reviews.each do |review| %>
          <li>投稿日時: <%= review.created_at %>　　　ゲームタイトル: <%= review.game.title %></li>
        <% end %>  
      <br>
      <br>
      <% end %>
    </ul>
    <%= paginate users %>
  </div>
<% end %>

app/views/users/maker_likes.html.erb
<div class="text-center">
    <h3>お気に入り一覧</h3>
    <br>
    <br>
    <br>
<ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= favindex_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favindex_user_path(@user)) %>">お気に入りユーザ</a></li>
      <li class="nav-item"><a href="<%= review_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(review_likes_user_path(@user)) %>">お気に入りレビュー</a></li>
      <li class="nav-item"><a href="<%= game_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(game_likes_user_path(@user)) %>">お気に入りゲームタイトル</a></li>
      <li class="nav-item"><a href="<%= maker_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(maker_likes_user_path(@user)) %>">お気に入り発売元メーカー</a></li>
</ul>

<%= render 'user_maker_likes', favmakers: @favmakers %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>game review</h1>
  <h4>会員登録画面</h4>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, 'プロフィール画像' %><br>
        <%= f.file_field :image %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認用' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登　録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/review_likes.html.erb
<div class="text-center">
    <h3>お気に入り一覧</h3>
    <br>
    <br>
    <br>
<ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= favindex_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favindex_user_path(@user)) %>">お気に入りユーザ</a></li>
      <li class="nav-item"><a href="<%= review_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(review_likes_user_path(@user)) %>">お気に入りレビュー</a></li>
      <li class="nav-item"><a href="<%= game_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(game_likes_user_path(@user)) %>">お気に入りゲームタイトル</a></li>
      <li class="nav-item"><a href="<%= maker_likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(maker_likes_user_path(@user)) %>">お気に入り発売元メーカー</a></li>
</ul>

<%= render 'user_review_likes', favreviews: @favreviews %>

app/views/users/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<% if logged_in? %>

<div class="text-center">
  <h1>ユーザ詳細</h1>
  <br>
  <br>
  <br>
  <ul class="list-unstyled">
    <li><%= image_tag @user.image.thumb.to_s %></li>
    <% if current_user == @user %>
      <li><%= link_to 'ユーザ情報編集', edit_user_path(@user), class: 'btn btn-sm btn-primary' %></li>
    <% else %>
    <% end %>
    <br>
    <li>ユーザネーム　<%= @user.name %></li>
    <br>
    <li><%= render 'favorites_users/follow_button', user: @user %></li>
    <br>
    <% if current_user == @user %>
    <li><%= link_to '新規レビュー投稿', new_review_path, class: 'btn btn-sm btn-primary' %></li>
    <% else %>
    <% end %>
    <br>
    <br>
    <h4>投稿したレビュー</h4>
      <% @reviews.each do |review| %>
      <br>
      <li>ゲームタイトル　<%= review.game.title %></li>
      <p><%= render 'favorites_games/like_button', game: review.game %></p>
      <li>発売元メーカー　<%= review.game.maker.maker %></li>
      <p><%= render 'favorites_makers/like_button', maker: review.game.maker %></p>
      <li>評価　<%= review.score %></li>
      <ul class="list-unstyled">
        <li>
          <p class="btn btn-info btn-sm" >レビューの表示・非表示</p>
          <ul class="list-unstyled" style="display: none;">
            <li class="content1-1">投稿日時　<%= review.created_at %></li>
            <li class="content1-2"><%= review.review %></li>
            <li class="content1-3"><%= render 'favorites_reviews/like_button', review: review %></li>
            <br>
          </ul>
        </li>
        <li>
          <p class="btn btn-info btn-sm">コメントの表示・非表示</p>
          <ul class="list-unstyled" style="display: none;">
            <li>
            <% comments = Comment.where(review_id: review.id) %>
            <% comments.each do |comment| %>
              投稿日時: <%= comment.created_at  %>　ユーザネーム: <%= comment.user.name  %>
              <br>
              コメント内容:　<%= comment.comment  %>
              <br>
              <br>
            <% end %>
            <%= link_to 'コメント投稿画面へ', new_review_comment_path(review.id), class: 'btn btn-sm btn-primary' %>
          </li>
          </ul>
        </li>
      </ul>
      <% if current_user == review.user %>
        <li><%= link_to '投稿編集', edit_review_path(review), class: 'btn btn-sm btn-primary' %></li>
        <br>
        <li><%= link_to "投稿削除", review, method: :delete, data: { confirm: "この投稿を削除してよろしいですか?" }, class: 'btn btn-danger btn-sm' %></li>
      <% end %>
      <br>
      <br>
      <br>
      <% end %>
  </ul>
</div>

<% else %>

<div class="text-center">
  <h1>ユーザ詳細</h1>
  <br>
  <br>
  <br>
  <ul class="list-unstyled">
    <li><%= image_tag @user.image.thumb.to_s %></li>
    <% if current_user == @user %>
      <li><%= link_to 'ユーザ情報編集', edit_user_path(@user), class: 'btn btn-sm btn-primary' %></li>
    <% else %>
    <% end %>
    <br>
    <li>ユーザネーム　<%= @user.name %></li>
    <br>
    <% if current_user == @user %>
    <li><%= link_to '新規レビュー投稿', new_review_path, class: 'btn btn-sm btn-primary' %></li>
    <% else %>
    <% end %>
    <br>
    <br>
    <h4>投稿したレビュー</h4>
      <% @reviews.each do |review| %>
      <br>
      <li>ゲームタイトル　<%= review.game.title %></li>
      <li>発売元メーカー　<%= review.game.maker.maker %></li>
      <li>評価　<%= review.score %></li>
      <ul class="list-unstyled">
        <li>
          <p class="btn btn-info btn-sm" >レビューの表示・非表示</p>
          <ul class="list-unstyled" style="display: none;">
            <li class="content1-1">投稿日時　<%= review.created_at %></li>
            <li class="content1-2"><%= review.review %></li>
            <br>
          </ul>
        </li>
        <li>
          <p class="btn btn-info btn-sm">コメントの表示・非表示</p>
          <ul class="list-unstyled" style="display: none;">
            <li>
            <% comments = Comment.where(review_id: review.id) %>
            <% comments.each do |comment| %>
              投稿日時: <%= comment.created_at  %>　ユーザネーム: <%= comment.user.name  %>
              <br>
              コメント内容:　<%= comment.comment  %>
              <br>
              <br>
            <% end %>
            <%= link_to 'コメント投稿画面へ', new_review_comment_path(review.id), class: 'btn btn-sm btn-primary' %>
          </li>
          </ul>
        </li>
      </ul>
      <% if current_user == review.user %>
        <li><%= link_to '投稿編集', edit_review_path(review), class: 'btn btn-sm btn-primary' %></li>
        <br>
        <li><%= link_to "投稿削除", review, method: :delete, data: { confirm: "この投稿を削除してよろしいですか?" }, class: 'btn btn-danger btn-sm' %></li>
      <% end %>
      <br>
      <br>
      <br>
      <% end %>
  </ul>
</div>

<% end %>

<script>
$(function(){
 
    //.accordion1の中のp要素がクリックされたら
	$('.list-unstyled p').click(function(){
 
		//クリックされた.accordion1の中のp要素に隣接するul要素が開いたり閉じたりする。
		$(this).next('ul').slideToggle();
 
	});
});
</script>