config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :review_likes
      get :game_likes
      get :maker_likes
      get :favindex
    end
  end
  
  
  
  resources :favorites_users, only: [:create, :destroy]
  resources :favorites_reviews, only: [:create, :destroy]
  resources :favorites_games, only: [:create, :destroy]
  resources :favorites_makers, only: [:create, :destroy]
  resources :makers, only: [:new, :create]
  resources :games, only: [:new, :create]
  resources :reviews, only: [:index, :new, :create, :destroy, :edit, :update] do
    resources :comments, only: [:new, :create]
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @reviews = Review.order(created_at: :desc).limit(5)
    
    reviews_averages = Review.group(:game_id).average(:score)
    @ranks = Hash[reviews_averages.sort_by{ |k, v| -v }]
  end
end

app/views/toppages/index.html.erb
<% if logged_in? %>
<div class="text-center">
  <h1>game review</h1>
    <br>
    <br>
    <br>
    
    <h3>新着のレビュー</h3>
    <ul class="list-unstyled">
      <% @reviews.each do |review| %>
        <li>投稿日時: <%= review.created_at %>　ユーザネーム: <%= review.user.name %></li>
        <li>ゲームタイトル: <%= review.game.title %>　　発売元メーカー: <%= review.game.maker.maker %>　<%= link_to 'このユーザのレビューを見る', user_path(review.user_id), class: 'btn btn-sm btn-primary' %></li>
      <br>
      <% end %>
    </ul>
    
    <h3>評価ランキング</h3>
    <ul class="list-unstyled">
      <% @ranks.first(5).each.with_index(1) do |(game_id, score), i| %>
      　<li>第 <%= i %> 位</li>
        <% top5 = Review.find_by(game_id: game_id) %>
        <li>ゲームタイトル: <%= top5.game.title %></li>
        <li>発売元メーカー: <%= top5.game.maker.maker %></li>
        <li>評価平均: <%= score.floor(2).to_f %></li>
      <% end %>
    </ul>
    
    <p><%= link_to 'レビュー一覧へ', reviews_path, class: 'btn btn-sm btn-primary' %></p>
</div>
  
<% else %>
  <div class="text-center">
  <h1>game review logo</h1>
    <br>
    <br>
    <br>
    <div class="text-center">
      <h4>ゲームのレビューの投稿、お気に入り機能はログインが必要です。</h4>
      <%= link_to 'ログイン', login_path, class: 'btn btn-lg btn-primary' %> or <%= link_to '会員登録', signup_path, class: 'btn btn-lg btn-primary' %>
      <br>
      <br>
      <br>
      
      <h3>新着のレビュー</h3>
    <ul class="list-unstyled">
      <% @reviews.each do |review| %>
       <li>投稿日時: <%= review.created_at %>　ユーザネーム: <%= review.user.name %></li>
       <li>ゲームタイトル: <%= review.game.title %>　　発売元メーカー: <%= review.game.maker.maker %>　<%= link_to 'このユーザのレビューを見る', user_path(review.user_id), class: 'btn btn-sm btn-primary' %></li>
      <br>
      <% end %>
    </ul>
    
    <h3>評価ランキング</h3>
    <ul class="list-unstyled">
      <% @ranks.first(5).each.with_index(1) do |(game_id, score), i| %>
      　<li>第 <%= i %> 位</li>
        <% top5 = Review.find_by(game_id: game_id) %>
        <li>ゲームタイトル: <%= top5.game.title %></li>
        <li>発売元メーカー: <%= top5.game.maker.maker %></li>
        <li>評価平均: <%= score.floor(2).to_f %></li>
      <% end %>
    </ul>
    
      <p><%= link_to 'レビュー一覧へ', reviews_path, class: 'btn btn-sm btn-primary' %></p>
  </div>
<% end %>