config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :review_likes
      get :game_likes
      get :maker_likes
      get :favindex
    end
  end
  
  
  
  resources :favorites_users, only: [:create, :destroy]
  resources :favorites_reviews, only: [:create, :destroy]
  resources :favorites_games, only: [:create, :destroy]
  resources :favorites_makers, only: [:create, :destroy]
  resources :makers, only: [:new, :create]
  resources :games, only: [:new, :create]
  resources :reviews, only: [:index, :new, :create, :destroy, :edit, :update] do
    resources :comments, only: [:new, :create]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :destroy, :edit, :update]
  before_action :correct_user, only: [:destroy, :edit, :update]
  
  def index
    @query = Review.order(id: :desc).ransack(params[:q])
    @reviews = @query.result(distinct: true).page(params[:page])
  end

  def new
    @review = Review.new
  end

  def create
    @review = current_user.review.build(review_params)
    if @review.save
      flash[:success] = 'レビューを投稿しました。'
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = 'レビューの投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    @review.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
 
    if @review.update(review_params)
      flash[:success] = 'レビューを編集しました。'
      render :edit
    else
      flash.now[:danger] = 'レビューの編集に失敗しました。'
    render :edit
    end   
  end
  
  private

  def review_params
    params.require(:review).permit(:game_id, :score, :review)
  end
  
  def correct_user
    @review = current_user.review.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end
end

app/views/reviews/edit.html.erb
<div class="text-center">
  <h4>既存レビュー編集</h4>
  <br>
  <br>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @review, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <p>ゲームタイトル　<%= @review.game.title %></p>
        <p>発売元メーカー　<%= @review.game.maker.maker %></p>
      </div>	   

      <div class="form-group">
        <%= f.label :score, '評価(1~5の0.5単位)' %>
        <%= f.number_field :score,min:1,max:5, step:0.5 %> 
      </div>

      <div class="form-group">
        <%= f.label :review, 'レビュー(500文字まで)' %>
        <%= f.text_area :review, class: 'form-control' %>
      </div>
      
      <%= f.submit '編集を完了する', class: 'btn btn-primary btn-sm' %>
      <br>
      <br>
      <%= link_to 'キャンセル', user_path(current_user), class: 'btn btn-sm btn-dark' %>
    <% end %>

  </div>
</div>

app/views/reviews/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<% if logged_in? %>

<div class="text-center">
  <h1>レビュー一覧</h1>
  <br>
  <br>
  <br>
  <ul class="list-unstyled">
    
    <%= search_form_for(@query, url: reviews_path) do |f| %>
      <%= f.label :user_name_or_game_title_or_game_maker_maker, "ユーザ,ゲーム,メーカーのいずれかで検索" %>
      <br>
      <%= f.search_field :user_name_or_game_title_or_game_maker_maker_cont %>
      <br>
      <br>
      <%= f.label :score, "評　価" %>
      <br>
      <%= f.search_field :score_gteq %>以上〜 <%= f.search_field :score_lt %>未満
      <br>
      <br>
      <%= f.submit %>
    <% end %>
    
    <br>
    <br>
    <% @reviews.each do |review| %>
    <li>ユーザネーム　<%= review.user.name %></li>
    <p><%= link_to 'ユーザ詳細へ', user_path(review.user), class: 'btn btn-sm btn-primary' %></p>
    <li>ゲームタイトル　<%= review.game.title %></li>
    <p><%= render 'favorites_games/like_button', game: review.game %></p>
    <li>発売元メーカー　<%= review.game.maker.maker %></li>
    <p><%= render 'favorites_makers/like_button', maker: review.game.maker %></p>
    <li>評価　<%= review.score %></li>
    <ul class="list-unstyled">
      <li>
        <p class="btn btn-info btn-sm" >レビューの表示・非表示</p>
        <ul class="list-unstyled" style="display: none;">
          <li class="content1-1">投稿日時　<%= review.created_at %></li>
          <li class="content1-2"><%= review.review %></li>
          <li class="content1-3"><%= render 'favorites_reviews/like_button', review: review %></li>
          <br>
        </ul>
      </li>
      <li>
        <p class="btn btn-info btn-sm">コメントの表示・非表示</p>
        <ul class="list-unstyled" style="display: none;">
          <li>
            <% comments = Comment.where(review_id: review.id) %>
            <% comments.each do |comment| %>
              投稿日時: <%= comment.created_at  %>　ユーザネーム: <%= comment.user.name  %>
              <br>
              コメント内容:　<%= comment.comment  %>
              <br>
              <br>
            <% end %>
            <%= link_to 'コメント投稿画面へ', new_review_comment_path(review.id), class: 'btn btn-sm btn-primary' %>
          </li>
        </ul>
      </li>
    </ul>
    <br>
    <br>
    <% end %>
    
  </ul>
  <%= paginate @reviews %>
</div>

<% else %>

<div class="text-center">
  <h1>レビュー一覧</h1>
  <br>
  <br>
  <br>
  <ul class="list-unstyled">
    
    <%= search_form_for(@query, url: reviews_path) do |f| %>
      <%= f.label :user_name_or_game_title_or_game_maker_maker, "ユーザ,ゲーム,メーカーのいずれかで検索" %>
      <br>
      <%= f.search_field :user_name_or_game_title_or_game_maker_maker_cont %>
      <br>
      <br>
      <%= f.label :score, "評　価" %>
      <br>
      <%= f.search_field :score_gteq %>以上〜 <%= f.search_field :score_lt %>未満
      <br>
      <br>
      <%= f.submit %>
    <% end %>
    
    <br>
    <br>
    <% @reviews.each do |review| %>
    <li>ユーザネーム　<%= review.user.name %></li>
    <li>ゲームタイトル　<%= review.game.title %></li>
    <li>発売元メーカー　<%= review.game.maker.maker %></li>
    <li>評価　<%= review.score %></li>
    <ul class="list-unstyled">
      <li>
        <p class="btn btn-info btn-sm" >レビューの表示・非表示</p>
        <ul class="list-unstyled" style="display: none;">
          <li class="content1-1">投稿日時　<%= review.created_at %></li>
          <li class="content1-2"><%= review.review %></li>
          <br>
        </ul>
      </li>
      <li>
        <p class="btn btn-info btn-sm">コメントの表示・非表示</p>
        <ul class="list-unstyled" style="display: none;">
          <li>
            <% comments = Comment.where(review_id: review.id) %>
            <% comments.each do |comment| %>
              投稿日時: <%= comment.created_at  %>　ユーザネーム: <%= comment.user.name  %>
              <br>
              コメント内容:　<%= comment.comment  %>
              <br>
              <br>
            <% end %>
            <%= link_to 'コメント投稿画面へ', new_review_comment_path(review.id), class: 'btn btn-sm btn-primary' %>
          </li>
        </ul>
      </li>
    </ul>
    <br>
    <br>
    <% end %>
    
  </ul>
  <%= paginate @reviews %>
</div>

<% end %>

<script>
$(function(){
 
    //.accordion1の中のp要素がクリックされたら
	$('.list-unstyled p').click(function(){
 
		//クリックされた.accordion1の中のp要素に隣接するul要素が開いたり閉じたりする。
		$(this).next('ul').slideToggle();
 
	});
});
</script>

app/views/reviews/new.html.erb
<div class="text-center">
  <h4>レビュー投稿</h4>
  <br>
  <br>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @review, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :game_id, 'ゲームタイトルを選択' %>
        <%= f.collection_select :game_id, Game.all, :id, :title %>
        <%= link_to '新規のゲーム登録はこちら', new_game_path, class: 'btn btn-sm btn-primary' %>
      </div>	   

      <div class="form-group">
        <%= f.label :score, '評価(1~5の0.5単位)' %>
        <%= f.number_field :score,min:1,max:5, step:0.5 %> 
      </div>

      <div class="form-group">
        <%= f.label :review, 'レビュー(500文字まで)' %>
        <%= f.text_area :review, class: 'form-control' %>
      </div>
      
      <%= f.submit '投稿', class: 'btn btn-primary btn-sm' %>
      <br>
      <br>
      <%= link_to 'キャンセル', user_path(current_user), class: 'btn btn-sm btn-dark' %>
    <% end %>

  </div>
</div>